s="Priyank Solanki"

print(len(s))
print(s)
print(s. capitalize())
print(s. casefold())
print(s.lower())
print(s.upper())
print(s.center(40,"*"))
print(s.count("o"))
print(s.endswith("ki"))
print(s.startswith("Pr"))
print(s.find("lan"))
print(s.index("i",2))
print("priy123".isalnum())
print("priy".isalnum())
print("123".isalnum())
print("priy 123".isalnum())
print("priy".isalpha())
print("123".isnumeric())
